<?php

namespace AppBundle\Repository;

/**
 * ProgrammingLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammingLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
