<?php

namespace AppBundle\Repository;

/**
 * ProjectViewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectViewRepository extends \Doctrine\ORM\EntityRepository
{
}
