<?php

namespace AppBundle\Repository;

/**
 * SiteTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteTextRepository extends \Doctrine\ORM\EntityRepository
{
}
